trigger:
- development

pool:
  name: BTPAgent
  demands:
   - Terraform -equals Yes

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    set BTP_USERNAME=perabathula.nagasiva@sap.com
    set BTP_PASSWORD=Allgodsofmexico27
    echo Terraform code is started deploying.
    echo executing the Terraform code in SAP BTP.......
    terraform --version
    terraform init
    terraform plan

  displayName: 'Run a multi-line script'
