general:
  verbose: true

stages:
  - name: Init
  - name: Plan
  - name: Apply

steps:
  Init:
    runSh:
      shell: bash
      script: |
        echo "Running Init"
        terraform init

  Plan:
    runSh:
      shell: bash
      script: |
        echo "Planning"
        terraform plan -out=tfplan

  Apply:
    runSh:
      shell: bash
      script: |
        echo "Applying"
        terraform apply -auto-approve tfplan
