stages:
  - name: TerraformInit
  - name: TerraformPlan
  - name: TerraformApply

steps:
  TerraformInit:
    runSh:
      shell: bash
      script: |
        terraform init

  TerraformPlan:
    runSh:
      shell: bash
      script: |
        terraform plan -out=tfplan

  TerraformApply:
    runSh:
      shell: bash
      script: |
        terraform apply -auto-approve tfplan

